<?php
session_start();
require_once '../connection.php';

if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    header("Location: login.php");
    exit;
}

if (!isset($_GET['id'])) {
    header("Location: managewaiter.php");
    exit;
}

$waiter_id = (int)$_GET['id'];
$pageTitle = "waiter Details";
$basePath = "../";
include '../_header.php';

try {
    // 1. Fetch waiter Profile
    $stmt = $pdo->prepare("SELECT * FROM staffs WHERE id = ?");
    $stmt->execute([$waiter_id]);
    $waiter = $stmt->fetch();

    if (!$waiter) die("waiter member not found.");

    // 2. Fetch Performance Stats (Total Orders & Total Revenue generated by this waiter)
    $stmtStats = $pdo->prepare("
        SELECT 
            COUNT(id) as total_orders,
            COALESCE(SUM(total_amount), 0) as total_revenue,
            MAX(created_at) as last_active
        FROM orders 
        WHERE user_id = ?
    ");
    $stmtStats->execute([$waiter_id]);
    $stats = $stmtStats->fetch();

    // 3. Fetch Recent Orders handled by this waiter
    $stmtOrders = $pdo->prepare("
        SELECT o.*, dt.table_number 
        FROM orders o
        JOIN dining_tables dt ON o.table_id = dt.id
        WHERE o.user_id = ?
        ORDER BY o.created_at DESC
        LIMIT 10
    ");
    $stmtOrders->execute([$waiter_id]);
    $recent_orders = $stmtOrders->fetchAll();

} catch (PDOException $e) {
    die("Error: " . $e->getMessage());
}
?>

<link rel="stylesheet" href="<?php echo $basePath; ?>css/viewOrders.css">
<link rel="stylesheet" href="<?php echo $basePath; ?>css/manageStaff.css">

<main class="main-wrapper">
    <div class="admin-container">
        <a href="manageStaff.php" class="back-link">← Back to Staff List</a>
        
        <div class="page-header">
            <h1>Staff Profile: <?php echo htmlspecialchars($waiter['username']); ?></h1>
        </div>

        <div class="waiter-detail-grid">
            
            <div class="profile-card">
                <div class="profile-header-img">
                    <img src="<?php echo $waiter['profile_picture'] ? $basePath . $waiter['profile_picture'] : $basePath.'uploads/Default_pfp.png'; ?>">
                </div>
                <h2><?php echo htmlspecialchars($waiter['username']); ?></h2>
                <span class="role-badge role-<?php echo $waiter['role']; ?>"><?php echo ucfirst($waiter['role']); ?></span>
                
                <div class="profile-info-list">
                    <div class="info-row">
                        <span>Email:</span>
                        <strong><?php echo htmlspecialchars($waiter['email']); ?></strong>
                    </div>
                    <div class="info-row">
                        <span>Joined:</span>
                        <strong><?php echo date("d M Y", strtotime($waiter['created_at'])); ?></strong>
                    </div>
                    <div class="info-row">
                        <span>User ID:</span>
                        <strong>#<?php echo $waiter['id']; ?></strong>
                    </div>
                </div>
            </div>

            <div class="stats-container">
                <div class="kpi-grid">
                    <div class="kpi-card">
                        <div class="kpi-label">Orders Handled</div>
                        <div class="kpi-value"><?php echo $stats['total_orders']; ?></div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-label">Revenue Generated</div>
                        <div class="kpi-value">RM <?php echo number_format($stats['total_revenue'], 2); ?></div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-label">Last Active</div>
                        <div class="kpi-value small">
                            <?php echo $stats['last_active'] ? date("d M, h:i A", strtotime($stats['last_active'])) : 'Never'; ?>
                        </div>
                    </div>
                </div>

                <h3 class="section-title" style="margin-top: 30px;">Recent Activity</h3>
                <div class="table-responsive">
                    <table>
                        <thead>
                            <tr>
                                <th>Order ID</th>
                                <th>Table</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (empty($recent_orders)): ?>
                                <tr><td colspan="5">No orders handled yet.</td></tr>
                            <?php else: ?>
                                <?php foreach ($recent_orders as $order): ?>
                                <tr>
                                    <td>#<?php echo $order['id']; ?></td>
                                    <td><?php echo $order['table_number']; ?></td>
                                    <td>RM <?php echo number_format($order['total_amount'], 2); ?></td>
                                    <td>
                                        <span class="status-badge status-<?php echo $order['status']; ?>">
                                            <?php echo ucfirst($order['status']); ?>
                                        </span>
                                    </td>
                                    <td><?php echo date("d M, H:i", strtotime($order['created_at'])); ?></td>
                                </tr>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>